-- ==============================
-- Supabase 建表 SQL
-- 在 Supabase Dashboard → SQL Editor 中执行
-- ==============================

-- 创建排课数据表
CREATE TABLE IF NOT EXISTS schedule_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,
  grade TEXT NOT NULL,
  subject TEXT NOT NULL,
  count INTEGER DEFAULT 0,
  season TEXT DEFAULT '暑',
  designer TEXT DEFAULT '',
  "subGrade" TEXT DEFAULT '',
  version TEXT DEFAULT '',
  lesson TEXT DEFAULT ''
);

-- 开启行级安全（RLS），允许所有匿名用户读写
ALTER TABLE schedule_entries ENABLE ROW LEVEL SECURITY;

-- 允许匿名用户读取
CREATE POLICY IF NOT EXISTS "Allow anonymous read" 
  ON schedule_entries FOR SELECT USING (true);

-- 允许匿名用户插入
CREATE POLICY IF NOT EXISTS "Allow anonymous insert" 
  ON schedule_entries FOR INSERT WITH CHECK (true);

-- 允许匿名用户更新
CREATE POLICY IF NOT EXISTS "Allow anonymous update" 
  ON schedule_entries FOR UPDATE USING (true) WITH CHECK (true);

-- 允许匿名用户删除
CREATE POLICY IF NOT EXISTS "Allow anonymous delete" 
  ON schedule_entries FOR DELETE USING (true);

-- 创建索引加速查询
CREATE INDEX IF NOT EXISTS idx_schedule_date ON schedule_entries(date);
CREATE INDEX IF NOT EXISTS idx_schedule_grade ON schedule_entries(grade);
CREATE INDEX IF NOT EXISTS idx_schedule_date_grade ON schedule_entries(date, grade);

-- 验证：查看表结构
-- SELECT * FROM schedule_entries LIMIT 5;
