-- 创建排课数据表
CREATE TABLE IF NOT EXISTS schedule_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,
  grade TEXT NOT NULL,
  subject TEXT NOT NULL,
  count INTEGER DEFAULT 0,
  season TEXT DEFAULT '暑',
  designer TEXT DEFAULT '',
  "subGrade" TEXT DEFAULT '',
  version TEXT DEFAULT '',
  lesson TEXT DEFAULT ''
);

-- 开启行级安全（RLS）
ALTER TABLE schedule_entries ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略（避免冲突）
DROP POLICY IF EXISTS "Allow anonymous read" ON schedule_entries;
DROP POLICY IF EXISTS "Allow anonymous insert" ON schedule_entries;
DROP POLICY IF EXISTS "Allow anonymous update" ON schedule_entries;
DROP POLICY IF EXISTS "Allow anonymous delete" ON schedule_entries;

-- 允许匿名用户读取
CREATE POLICY "Allow anonymous read"
  ON schedule_entries FOR SELECT USING (true);

-- 允许匿名用户插入
CREATE POLICY "Allow anonymous insert"
  ON schedule_entries FOR INSERT WITH CHECK (true);

-- 允许匿名用户更新
CREATE POLICY "Allow anonymous update"
  ON schedule_entries FOR UPDATE USING (true) WITH CHECK (true);

-- 允许匿名用户删除
CREATE POLICY "Allow anonymous delete"
  ON schedule_entries FOR DELETE USING (true);

-- 创建索引加速查询
CREATE INDEX IF NOT EXISTS idx_schedule_date ON schedule_entries(date);
CREATE INDEX IF NOT EXISTS idx_schedule_grade ON schedule_entries(grade);
